### ISSUE TITLE
Failed to create new session with old Selenium clients

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/ggr#100]
With Selenium 2.47.1 when creating a new session with 1.2.4:

```
2017-07-13 14:54:33,954 DEBUG headers - http-outgoing-0 << HTTP/1.1 200 OK
2017-07-13 14:54:33,954 DEBUG headers - http-outgoing-0 << Server: nginx
2017-07-13 14:54:33,954 DEBUG headers - http-outgoing-0 << Date: Thu, 13 Jul 2017 11:54:34 GMT
2017-07-13 14:54:33,954 DEBUG headers - http-outgoing-0 << Content-Type: application/json
2017-07-13 14:54:33,954 DEBUG headers - http-outgoing-0 << Transfer-Encoding: chunked
2017-07-13 14:54:33,954 DEBUG headers - http-outgoing-0 << Connection: keep-alive
2017-07-13 14:54:33,954 DEBUG headers - http-outgoing-0 << Access-Control-Allow-Methods: GET,PUT,OPTIONS,POST,DELETE
2017-07-13 14:54:33,954 DEBUG headers - http-outgoing-0 << Access-Control-Allow-Origin: *
2017-07-13 14:54:33,954 DEBUG headers - http-outgoing-0 << Access-Control-Allow-Headers: Content-Type,Authorization
2017-07-13 14:54:33,954 DEBUG headers - http-outgoing-0 << Access-Control-Allow-Credentials: true
2017-07-13 14:54:33,954 DEBUG headers - http-outgoing-0 << Set-Cookie: uid=CmajrVlnX3q8S3PSkUzPAg==; path=/
2017-07-13 14:54:33,954 DEBUG headers - http-outgoing-0 << Content-Encoding: gzip
2017-07-13 14:54:33,957 DEBUG MainClientExec - Connection can be kept alive indefinitely
2017-07-13 14:54:33,957 DEBUG HttpAuthenticator - Authentication succeeded
2017-07-13 14:54:33,958 DEBUG TargetAuthenticationStrategy - Caching 'basic' auth scheme for http://sg.yandex-team.ru:4444
2017-07-13 14:54:33,971 DEBUG ResponseProcessCookies - Cookie accepted [uid="CmajrVlnX3q8S3PSkUzPAg==", version:0, domain:sg.yandex-team.ru, path:/, expiry:null]
2017-07-13 14:54:33,974 DEBUG PoolingHttpClientConnectionManager - Connection [id: 0][route: {}->http://sg.yandex-team.ru:4444] can be kept alive indefinitely
2017-07-13 14:54:33,974 DEBUG PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {}->http://sg.yandex-team.ru:4444][total kept alive: 1; route allocated: 1 of 2000; total allocated: 1 of 2000]

java.lang.NullPointerException
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:246)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:155)
	at ru.yandex.qatools.test.SeleniumTest.openDriver(SeleniumTest.java:299)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by vania-pooh** [comment]
Works with 1.2.2.
