### ISSUE TITLE
ggr crashed after first request

### ISSUE THREAD

**Issue by superTes** [aerokube/ggr#181]
execute start ggr
```
./ggr_darwin_amd64 -quotaDir ./ -users ./
```
quota.xml
```
<qa:browsers xmlns:qa="urn:config.gridrouter.qatools.ru">
<browser name="internet explorer" defaultVersion="11">
    <version number="11">
        <region name="1">
            <host name="127.0.0.1" port="10259" count="3"/>
        </region>
    </version>
</browser>
<browser name="chrome" defaultVersion="65">
    <version number="65">
        <region name="1">
            <host name="127.0.0.1" port="10259" count="3"/>
        </region>
    </version>
</browser>
<browser name="firefox" defaultVersion="59">
    <version number="59">
        <region name="1">
            <host name="127.0.0.1" port="10259" count="3"/>
        </region>
    </version>
</browser>
</qa:browsers>
```

users.htpasswd was genered by ```htpasswd -bc /<path.to.my.dir>/.htpasswd test test-password``` command 

request url is 'http://test:test-password@localhost:4444/wd/hub'

```
2018/03/21 12:04:44 [-] [-] [INIT] [-] [-] [-] [-] [-] [-] [Users file is "./"]
2018/03/21 12:04:44 [-] [-] [INIT] [-] [-] [-] [-] [-] [-] [Loading configuration files from "./"]panic: read ./: is a directory

goroutine 35 [running]:
github.com/aerokube/ggr/vendor/github.com/abbot/go-http-auth.reload_htpasswd(0xc420144000)
        /home/travis/gopath/src/github.com/aerokube/ggr/vendor/github.com/abbot/go-http-auth/users.go:125 +0x3ffgithub.com/aerokube/ggr/vendor/github.com/abbot/go-http-auth.HtpasswdFileProvider.func1()
        /home/travis/gopath/src/github.com/aerokube/ggr/vendor/github.com/abbot/go-http-auth/users.go:143 +0x2a
github.com/aerokube/ggr/vendor/github.com/abbot/go-http-auth.(*File).ReloadIfNeeded(0xc420144000)        /home/travis/gopath/src/github.com/aerokube/ggr/vendor/github.com/abbot/go-http-auth/users.go:38 +0xde
github.com/aerokube/ggr/vendor/github.com/abbot/go-http-auth.HtpasswdFileProvider.func2(0xc4201760c0, 0x4, 0x1329611, 0x14, 0x2, 0xc42014
81a0)
        /home/travis/gopath/src/github.com/aerokube/ggr/vendor/github.com/abbot/go-http-auth/users.go:145 +0x35
github.com/aerokube/ggr/vendor/github.com/abbot/go-http-auth.(*BasicAuth).CheckAuth(0xc420148000, 0xc420174100, 0xc4201460e0, 0xc42015a70
0)
        /home/travis/gopath/src/github.com/aerokube/ggr/vendor/github.com/abbot/go-http-auth/basic.go:83 +0x1e7
github.com/aerokube/ggr/vendor/github.com/abbot/go-http-auth.(*BasicAuth).Wrap.func1(0x14928e0, 0xc42017c000, 0xc420174100)
        /home/travis/gopath/src/github.com/aerokube/ggr/vendor/github.com/abbot/go-http-auth/basic.go:142 +0x46
main.WithSuitableAuthentication.func1(0x14928e0, 0xc42017c000, 0xc420174100)
        /home/travis/gopath/src/github.com/aerokube/ggr/proxy.go:493 +0x346
main.withCloseNotifier.func1.1(0xc420148080, 0x14928e0, 0xc42017c000, 0xc420174000, 0x1492da0, 0xc4201502c0, 0xc4201460d0)        /home/travis/gopath/src/github.com/aerokube/ggr/proxy.go:421 +0x66
created by main.withCloseNotifier.func1
        /home/travis/gopath/src/github.com/aerokube/ggr/proxy.go:420 +0xdb
```

**Comment by vania-pooh** [comment]
@superTes `-users` should point to file, not directory.

**Comment by superTes** [comment]
@vania-pooh yes, i saw this in doc,  but, will you handle this?

**Comment by vania-pooh** [comment]
@superTes this is an issue in external library. Need to investigate - what can be done with it.

**Comment by superTes** [comment]
@vania-pooh ok, thanks
