### ISSUE TITLE
ggr docker start issue

### ISSUE THREAD

**Issue by narayannewworld** [aerokube/ggr#184]
I  have created selenium hub and node .. i have also created quotes directory as well as test.xml file in proper location .. also given 777 permissions .. but still below router creation failed.

docker run -d --name ggr -v /etc/grid-router/:/etc/grid-router:ro --net host aerokube/ggr:latest-release

[root@cherishlocalhost quota]# docker run -d --name ggr -v /etc/grid-router/:/etc/grid-router:ro --net host aerokube/ggr:latest-release
524a34207a46657de84183fb94c5705e64bc5ce8d13524348d8a5b7794e37427
[root@cherishlocalhost quota]# docker ps -a
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS                     PORTS                    NAMES
524a34207a46        aerokube/ggr:latest-release            "/usr/bin/ggr -lis..."   3 seconds ago       Exited (1) 2

root@cherishlocalhost quota]# docker run -it aerokube/ggr:latest-release
2018/03/26 21:31:27 [-] [-] [INIT] [-] [-] [-] [-] [-] [-] [Users file is "/etc/grid-router/users.htpasswd"]
2018/03/26 21:31:27 [-] [-] [INIT] [-] [-] [-] [-] [-] [-] [Users file "/etc/grid-router/users.htpasswd" does not exist]

**Comment by narayannewworld** [comment]
root@cherishlocalhost /]# cd /etc/grid-router/
[root@cherishlocalhost grid-router]# ls -ltr
total 4
-rwxrwxrwx. 1 root root 43 Mar 26 22:27 users.htpasswd
drwxrwxrwx. 2 root root 22 Mar 26 22:30 quota
[root@cherishlocalhost grid-router]#

**Comment by narayannewworld** [comment]
I am able to start all services.. but when i hit the url : http://test:test-password@localhost:4444/wd/hub ---> i am getting below error: Please help me if this is expected one.

404 page not found

**Comment by aandryashin** [comment]
the http://test:test-password@localhost:4444/wd/hub url is for tests, there
is nothing to display in the browser...

2018-03-27 1:12 GMT+03:00 narayannewworld <notifications@github.com>:

**Comment by vania-pooh** [comment]
@narayannewworld so this is the expected behavior. :)

**Comment by narayannewworld** [comment]
Thanks so much for your reply.

**Comment by narayannewworld** [comment]
ping also working : but getting below error when i try to run the test : Can you please advise ...


Connecting to selenium grid: http://test:Password18@<IP_AddFRess>:4444/wd/hub
Desired capabilities: Capabilities [{acceptSslCerts=true, marionette=org.openqa.selenium.firefox.FirefoxProfile@dcfda20, acceptInsecureCerts=true, browserName=firefox, version=, platform=ANY}]
Skipped step
Skipped step
Skipped step
Skipped steporg.openqa.selenium.WebDriverException: Unable to parse remote response: 401 Unauthorized
Connecting to selenium grid: http://test:Password18@<IP_Address>:4444/wd/hub
Desired capabilities: Capabilities [{acceptSslCerts=true, marionette=org.openqa.selenium.firefox.FirefoxProfile@3ec11999, acceptInsecureCerts=true, browserName=firefox, version=, platform=ANY}]

**Comment by vania-pooh** [comment]
@narayannewworld did you create `users.htpasswd` file?

**Comment by narayannewworld** [comment]
yes i did ...

**Comment by narayannewworld** [comment]
total 4
-rw-r--r-- 1 root root 16 Mar 27 14:56 users.htpasswd
drwxr-xr-x 2 root root 60 Mar 27 15:26 quota

**Comment by narayannewworld** [comment]
http://test:Password18@<IP_Address>:4444/wd/hub . -- here Password18 is the password i stored in the file users.htpasswd

**Comment by vania-pooh** [comment]
@narayannewworld could you provide an exact command used to create this file? Also what's inside Ggr logs? There should be a message specifying path to users file.

**Comment by narayannewworld** [comment]
I used below command to to create the password file:

htpasswd -bc /etc/grid-router/users.htpasswd test test-password

but here once the file created i have edited users.htpasswd file and updated the password to "Password18"( if fact i tried with default password which got created when i execute the above command but still not worked.. so i simplified the the password to "Password18"

**Comment by narayannewworld** [comment]
+ more info:

 grid-router]# docker logs fbccd86a64ed
2018/03/27 15:46:30 [-] [-] [INIT] [-] [-] [-] [-] [-] [-] [Users file is "/etc/grid-router/users.htpasswd"]
2018/03/27 15:46:30 [-] [-] [INIT] [-] [-] [-] [-] [-] [-] [Loading configuration files from "/etc/grid-router/quota"]
[root@srvjmpvlsk00 grid-router]

**Comment by vania-pooh** [comment]
@narayannewworld passwords are stored in encrypted form. So you should create it like this:
```
$ htpasswd -bc /etc/grid-router/users.htpasswd test Password18
```

**Comment by narayannewworld** [comment]
Thanks Vania .. I can see now requests are passing to hub and but testing is failing with below error.

my sincere apologies for posting one by one error ... but you are the best and great.. Can you pls check below error and help me if you see any issues.

org.openqa.selenium.WebDriverException: cannot create session firefox-59.0.1 on any hosts after 1 attempt(s), last host error was: Error forwarding the new session cannot find : Capabilities {acceptInsecureCerts: true, acceptSslCerts: true, browserName: firefox, marionette: UEsDBBQACAgIAMKJfEwAAAAAAAA..., version: 59.0.1} (WARNING: The server did not provide any stacktrace information)
Connecting to selenium grid: http://test:test-password@***************:4444/wd/hub
Desired capabilities: Capabilities [{acceptSslCerts=true, marionette=org.openqa.selenium.firefox.FirefoxProfile@14c01636, acceptInsecureCerts=true, browserName=firefox, version=, platform=ANY}]
Command duration or timeout: 123 milliseconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: '*****************', ip: 'fe80:0:0:0:18f6:8fc8:935:364e%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_144'
Driver info: driver.version: RemoteWebDriver
                at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

**Comment by vania-pooh** [comment]
@narayannewworld browser names and version on the upstream hub should match exactly to what is specified in quota files. E.g. if in XML you have:
```
<browser name="firefox" defaultVersion="59.0">
    <version number="59.0">
        <region name="1">
            <host name="host1.example.com" port="4444" count="1"/>
        </region>
</browser>
```
... then you should have `firefox` version `59.0` on `host1.example.com:4444`. This is all about matching strings.

**Comment by narayannewworld** [comment]
Here is my .xml file ...

<qa:browsers xmlns:qa="urn:config.gridrouter.qatools.ru">
<browser name="firefox" defaultVersion="59.0">
    <version number="59.0">
        <region name="1">
            <host name="IP" port="4445" count="1"/>
        </region>
    </version>
</browser>
<browser name="chrome" defaultVersion="65.0.3325.162">
    <version number="65.0.3325.162">
        <region name="1">
            <host name="IP" port="4445" count="1"/>
        </region>
    </version>
</browser>
</qa:browsers>

**Comment by narayannewworld** [comment]
Here is my xml file:

---<qa:browsers xmlns:qa="urn:config.gridrouter.qatools.ru">
-----<browser name="firefox" defaultVersion="59.0">
  ----  <version number="59.0">
        ---<region name="1">
           --- <host name="10.46.0.102" port="4445" count="1"/>
       -- </region>
    </version>
</browser>
<browser name="chrome" defaultVersion="65.0.3325.162">
    <version number="65.0.3325.162">
        <region name="1">
            <host name="10.46.0.102" port="4445" count="1"/>
        </region>
    </version>
</browser>
</qa:browsers>

**Comment by narayannewworld** [comment]
<img width="400" alt="screen shot 2018-03-29 at 10 52 38" src="https://user-images.githubusercontent.com/31776070/38082704-60c641e0-333f-11e8-9ffc-699de5b48b1e.png">

**Comment by narayannewworld** [comment]
i have pasted my .xml file above.. but still getting below error:

g.openqa.selenium.WebDriverException: unsupported browser: firefox (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 194 milliseconds

**Comment by vania-pooh** [comment]
@narayannewworld when changing XML files you have to either restart Ggr container or reload its configuration via:
```
$ docker kill -s HUP ggr
```
An error you are getting means - "don't know about browser with name firefox".

**Comment by narayannewworld** [comment]
Yes.. Thanks so much,.. some how the firefox is not working but we are able to to complete the testing in chrome browser .

i used below docker's to build chrome.

$ docker network create grid
$ docker run -d -p 4445:4444 --net grid --name selenium-hub selenium/hub:3.11.0-bismuth
$ docker run -d --net grid -e HUB_HOST=selenium-hub -v /dev/shm:/dev/shm selenium/node-chrome:3.11.0-bismuth
$ docker run -d --net grid -e HUB_HOST=selenium-hub -v /dev/shm:/dev/shm selenium/node-firefox:3.11.0-bismuth

**Comment by vania-pooh** [comment]
@narayannewworld also take a look at [Selenoid](https://github.com/aerokube/selenoid) project. :)

**Comment by vania-pooh** [comment]
@narayannewworld any more things to do here?

**Comment by vania-pooh** [comment]
Closing because of inactivity. Feel free to reopen if any questions are remaining.

**Comment by tbhatt-apttus** [comment]
Hello @vania-pooh ,

I am still facing issue in setup. After starting ggr, i am trying to hit the following url
http://test:test-password@localhost:4444/wd/hub
but not able to load the page.  Can you help  here?
I am using windows machine.

**Comment by vania-pooh** [comment]
@tbhatt-apttus take a look at Ggr logs with`docker logs ggr`.
