### ISSUE TITLE
The program exit if you just have a guests file and no users

### ISSUE THREAD

**Issue by asquel** [aerokube/ggr#215]
The program exits completely if you just have a guests xml file and no users.htpasswd

```
2018/05/31 13:18:57 [-] [-] [INIT] [-] [-] [-] [-] [-] [-] [Loading configuration files from "/etc/grid-router/quota"]
panic: stat /etc/grid-router/users.htpasswd: no such file or directory

goroutine 10 [running]:
github.com/aerokube/ggr/vendor/github.com/abbot/go-http-auth.(*File).ReloadIfNeeded(0xc420060410)
	/home/travis/gopath/src/github.com/aerokube/ggr/vendor/github.com/abbot/go-http-auth/users.go:32 +0x1ae
github.com/aerokube/ggr/vendor/github.com/abbot/go-http-auth.HtpasswdFileProvider.func2(0xc42005c210, 0x12, 0x71a7c7, 0x14, 0x2, 0xc4200c9100)
	/home/travis/gopath/src/github.com/aerokube/ggr/vendor/github.com/abbot/go-http-auth/users.go:145 +0x35
github.com/aerokube/ggr/vendor/github.com/abbot/go-http-auth.(*BasicAuth).CheckAuth(0xc4200c8f20, 0xc420124100, 0xc420040f50, 0xc420024700)
	/home/travis/gopath/src/github.com/aerokube/ggr/vendor/github.com/abbot/go-http-auth/basic.go:83 +0x1e7
github.com/aerokube/ggr/vendor/github.com/abbot/go-http-auth.(*BasicAuth).Wrap.func1(0x87c5c0, 0xc420126000, 0xc420124100)
	/home/travis/gopath/src/github.com/aerokube/ggr/vendor/github.com/abbot/go-http-auth/basic.go:142 +0x46
main.WithSuitableAuthentication.func1(0x87c5c0, 0xc420126000, 0xc420124100)
	/home/travis/gopath/src/github.com/aerokube/ggr/proxy.go:559 +0x98
main.withCloseNotifier.func1.1(0xc4200c8fa0, 0x87c5c0, 0xc420126000, 0xc420124000, 0x87ca80, 0xc420043840, 0xc420040f40)
	/home/travis/gopath/src/github.com/aerokube/ggr/proxy.go:474 +0x66
created by main.withCloseNotifier.func1
	/home/travis/gopath/src/github.com/aerokube/ggr/proxy.go:473 +0xdb

```

**Comment by vania-pooh** [comment]
@asquel duplicates #191.

**Comment by vania-pooh** [comment]
We'll do our best to fix in next release.
