### ISSUE TITLE
Panic after running two weeks

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/ggr#75]
```
Jun  6 03:24:54 localhost docker/ggr[973]: 2017/06/06 03:24:54 http: multiple response.WriteHeader calls
Jun  6 03:24:54 localhost docker/ggr[973]: fatal error: concurrent map read and map write
Jun  6 03:24:55 localhost docker/ggr[973]:
Jun  6 03:24:55 localhost docker/ggr[973]: goroutine 945630237 [running]:
Jun  6 03:24:55 localhost docker/ggr[973]: runtime.throw(0x713be1, 0x21)
Jun  6 03:24:55 localhost docker/ggr[973]: #011/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/panic.go:596 +0x95 fp=0xc42866f9f8 sp=0xc42866f9d8
Jun  6 03:24:55 localhost docker/ggr[973]: runtime.mapaccess2_faststr(0x6e91a0, 0xc429672ba0, 0x70bbd8, 0xa, 0xc42994dd99, 0x1)
Jun  6 03:24:55 localhost docker/ggr[973]: #011/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/hashmap_fast.go:326 +0x50a fp=0xc42866fa58 sp=0xc42866f9f8
Jun  6 03:24:55 localhost docker/ggr[973]: net/http.(*chunkWriter).writeHeader.func1(0x70bbd8, 0xa)
Jun  6 03:24:55 localhost docker/ggr[973]: #011/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/http/server.go:1157 +0x63 fp=0xc42866fab0 sp=0xc42866fa58
Jun  6 03:24:55 localhost docker/ggr[973]: net/http.(*chunkWriter).writeHeader(0xc42994dd18, 0x0, 0x0, 0x0)
Jun  6 03:24:55 localhost docker/ggr[973]: #011/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/http/server.go:1303 +0x10c7 fp=0xc42866fce8 sp=0xc42866fab0
Jun  6 03:24:55 localhost docker/ggr[973]: net/http.(*chunkWriter).close(0xc42994dd18)
Jun  6 03:24:55 localhost docker/ggr[973]: #011/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/http/server.go:379 +0xf6 fp=0xc42866fd30 sp=0xc42866fce8
Jun  6 03:24:55 localhost docker/ggr[973]: net/http.(*response).finishRequest(0xc42994dce0)
Jun  6 03:24:55 localhost docker/ggr[973]: #011/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/http/server.go:1540 +0x7a fp=0xc42866fd58 sp=0xc42866fd30
Jun  6 03:24:55 localhost docker/ggr[973]: net/http.(*conn).serve(0xc434e38500, 0x8466e0, 0xc422ca7f80)
Jun  6 03:24:55 localhost docker/ggr[973]: #011/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/http/server.go:1830 +0x652 fp=0xc42866ffc8 sp=0xc42866fd58
Jun  6 03:24:55 localhost docker/ggr[973]: runtime.goexit()
Jun  6 03:24:55 localhost docker/ggr[973]: #011/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42866ffd0 sp=0xc42866ffc8
Jun  6 03:24:55 localhost docker/ggr[973]: created by net/http.(*Server).Serve
Jun  6 03:24:55 localhost docker/ggr[973]: #011/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/http/server.go:2668 +0x2ce
Jun  6 03:24:55 localhost docker/ggr[973]:
Jun  6 03:24:55 localhost docker/ggr[973]: goroutine 1 [select, 29369 minutes]:
Jun  6 03:24:55 localhost docker/ggr[973]: github.com/aerokube/ggr/vendor/github.com/facebookgo/grace/gracehttp.Serve(0xc42000c030, 0x1, 0x1, 0xc420014fd0, 0x0)
Jun  6 03:24:55 localhost docker/ggr[973]: #011/home/travis/gopath/src/github.com/aerokube/ggr/vendor/github.com/facebookgo/grace/gracehttp/http.go:162 +0x5e6
Jun  6 03:24:55 localhost docker/ggr[973]: main.main()
Jun  6 03:24:55 localhost docker/ggr[973]: #011/home/travis/gopath/src/github.com/aerokube/ggr/main.go:101 +0xe3
```
Full log in attachment. Seems to be an issue in GraceHTTP - in that case we can just close the issue. But need to check.
[panic.tar.gz](https://github.com/aerokube/ggr/files/1053810/panic.tar.gz)

**Comment by vania-pooh** [comment]
Seems to be caused by GraceHttp removed in 1.2.2.

**Comment by vania-pooh** [comment]
Can't reproduce.
